### ISSUE TITLE
Some site's colors are too bright, even with prefer dark mode on & allow light tab bar off

### ISSUE THREAD

**Issue by Freeplayg** [easonwong-de/Adaptive-Tab-Bar-Colour#29]
Example from Mastodon:
![image](https://user-images.githubusercontent.com/40742947/183309138-bd649053-a5a5-4d10-987e-048f48d9e91a.png)

**Comment by Freeplayg** [comment]
Actually, maybe instead add the option to ignore the site's theme color, and just use the website's background color?

**Comment by YS-Wong** [comment]
Hello!

As a matter of fact, another user also wanted to change the threshold of dark/light color in #27, but in the opposite way: they wanted the add-on to classify more colors as dark color. Now, the add-on decides whether a color is bright or dark (affects text color) in this way: brightness = 0.299 × r + 0.587 × g + 0.114 × b; if brightness > 128, then color is bright; otherwise is it dark. This procedure is based on science and I might not change it once more.

If you don’t like the theme color, please open settings page of the add-on (open pop-up, and click “More settings…”), turn on “Set color for specific domains”. Then you may click “Add” symbol at the end of the list, paste the domain to replace “example.com”, and then choose “ignore theme color” in the dropdown menu. (In future version it’ll be easier to do)

Hope this solves your problem.

**Comment by CennoxX** [comment]
It would be great, if this threshold of currently 128 could be set in the preferences.

**Comment by Erudition** [comment]
> brightness = 0.299 × r + 0.587 × g + 0.114 × b; if brightness > 128, then color is bright; otherwise is it dark. This procedure is based on science and might not be changed in the foreseeable future.

I can imagine 2 alternatives that might end up being better:
1. Convert the color to [Oklch ](https://oklch.com/) and use the lightness from that - the lab color space [is better anyway](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl), but it's ideal for this since the perceived brightness is right there in the data - whereas rgb brightness is inconsistent depending on the color.
2. Use a good [color contrast algorithm](https://ruitina.com/apca-accessible-colour-contrast/) to compare the contrast of the color on the designated "dark" color vs. the designated "light" color.

**Comment by easonwong-de** [comment]
I introduced a system where the user can set the minimum contrast ratio for Firefox UI. If the ratio is not met, the colour given by ATBC will be adjusted.

The contrast ratio is calculated by:

$`\text{Contrast ratio} = \frac{\text{Relative luminance}_\text{lighter colour} \cdot 255 + 12.75}{\text{Relative luminance}_\text{darker colour} \cdot 255 + 12.75}`$

with $`\text{Relative luminance} \cdot 255 = 0.2126 \cdot L_R + 0.7152 \cdot L_G + 0.0722 \cdot L_B`$

On theory, $L_R$, $L_G$, and $L_B$ are calculated with:

$`L(x) =
\begin{cases} 
\frac{x}{3294.6} & \text{if } x \leq 10.3148, \\
\left(\frac{x + 14.0250}{269.0250}\right)^{2.4} & \text{otherwise}.
\end{cases}
`$

with $x$ being the sRGB value of R, G, or B (0 – 255).

I approximated the equation into:

$`\text{L}(x) =
\begin{cases} 
0.0000 & \text{if } x < 0, \\
0.1151 \cdot x & \text{if } 0 \leq x < 32, \\
0.2935 \cdot x - 5.7074 & \text{if } 32 \leq x < 64, \\
0.5236 \cdot x - 20.4339 & \text{if } 64 \leq x < 96, \\
0.7880 \cdot x - 45.8232 & \text{if } 96 \leq x < 128, \\
1.0811 \cdot x - 83.3411 & \text{if } 128 \leq x < 160, \\
1.3992 \cdot x - 134.2269 & \text{if } 160 \leq x < 192, \\
1.7395 \cdot x - 199.5679 & \text{if } 192 \leq x < 224, \\
2.1001 \cdot x - 280.3410 & \text{if } 224 \leq x < 256, \\
255.0000 & \text{if } x \geq 256.
\end{cases}`$

If the contrast ratio does not reach the set value, a dimming / lightening filter will be applied on the colour:

$`\text{dim\%} =
\begin{cases} 
\frac{ \left(\frac{\text{Minimum contrast}}{\text{Actual contrast}} - 1\right) \cdot \left(\text{Relative luminance} + 0.05\right)}{1 -  \text{Relative luminance}} & \text{in light mode} \\
\frac{\text{Current contrast}}{\text{Minimum contrast}} - 1 & \text{in dark mode}
\end{cases}`$

**Comment by easonwong-de** [comment]
P.S. v2.2 is still awaiting review.

**Comment by easonwong-de** [comment]
With the upcoming v2.2, I introduced a system where the user can set the minimum contrast ratio for Firefox UI. If the ratio is not met, the colour given by ATBC will be adjusted.

The contrast ratio is calculated by:

$`\text{Contrast ratio} = \frac{255 \cdot \text{Relative luminance}_\text{lighter colour} + 12.75}{255 \cdot \text{Relative luminance}_\text{darker colour} + 12.75}`$

with $`255 \cdot \text{Relative luminance} = 0.2126 \cdot L_R + 0.7152 \cdot L_G + 0.0722 \cdot L_B`$

In theory, $L_R$, $L_G$, and $L_B$ are calculated with:

$`L(x) =
\begin{cases} 
\frac{x}{3294.6} & \text{if } x \leq 10.3148, \\
\left(\frac{x + 14.0250}{269.0250}\right)^{2.4} & \text{otherwise}.
\end{cases}
`$

with $x$ being the sRGB value of R, G, or B (0 – 255).

I approximated the equation into:

$`\text{L}(x) =
\begin{cases} 
0.0000 & \text{if } x < 0, \\
0.1151 \cdot x & \text{if } 0 \leq x < 32, \\
0.2935 \cdot x - 5.7074 & \text{if } 32 \leq x < 64, \\
0.5236 \cdot x - 20.4339 & \text{if } 64 \leq x < 96, \\
0.7880 \cdot x - 45.8232 & \text{if } 96 \leq x < 128, \\
1.0811 \cdot x - 83.3411 & \text{if } 128 \leq x < 160, \\
1.3992 \cdot x - 134.2269 & \text{if } 160 \leq x < 192, \\
1.7395 \cdot x - 199.5679 & \text{if } 192 \leq x < 224, \\
2.1001 \cdot x - 280.3410 & \text{if } 224 \leq x < 256, \\
255.0000 & \text{if } x \geq 256.
\end{cases}`$

If the contrast ratio does not reach the set value, a dimming / lightening filter will be applied to the colour:

$`\text{dim\%} =
\begin{cases} 
\frac{ \left(\frac{\text{Minimum contrast}}{\text{Actual contrast}} - 1\right) \cdot \left(\text{Relative luminance} + 0.05\right)}{1 -  \text{Relative luminance}} & \text{in light mode} \\
\frac{\text{Actual contrast}}{\text{Minimum contrast}} - 1 & \text{in dark mode}
\end{cases}`$

P.S. v2.2 is still awaiting review.
