### ISSUE TITLE
Plugin + Custom CSS causes some menu's to be transparent

### ISSUE THREAD

**Issue by advanced03** [easonwong-de/Adaptive-Tab-Bar-Colour#63]
**Firefox Version:** 
118.0.1

**Bug Description:**
If I use my custom css theme and this addon, some firefox menu's will become transparent. Removing the plugin causes the menu's to lo
![Screenshot 2023-10-09 120713](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/63119810/c3a48f7e-d7be-401a-9dba-c8a1f23c9eb8)
ok normal again.

**Steps to Reproduce:**
1. Install the plugin with fluent design themes

**Comment by nikkehtine** [comment]
I have the same problem but with the toolbar. I believe it's caused by the extension setting the color to transparent, because when you set the slider to one tick, the problem disappears.
![obraz](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/27138416/c83c4d61-1bfb-4d50-a209-7219c336d9f4)
![obraz](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/27138416/864af59c-d292-4489-93b1-f0fa8edcb000)

**Comment by easonwong-de** [comment]
The new version, v2.2 (awaiting review by Mozilla), will give Firefox solid colours, thus will solve the problem.
